version: '3.8'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - ./.env
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
  wordpress:
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
       mariadb:
        condition: service_healthy
    restart: on-failure
    expose:
      - "9000"
    env_file:
      - ./.env
  nginx:
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "443:443"
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ./mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ./wordpress_data
      o: bind