version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: srcs/nginx/Dockerfile
    ports:
      - "443:443"
    networks:
      - mynetwork
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: srcs/wordpress/Dockerfile
    networks:
      - mynetwork
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: srcs/mariadb/Dockerfile
    networks:
      - mynetwork
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_name
      - db_user
      - db_password
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  wordpress_data:
  mariadb_data:

secrets:
  db_root_password:
    file: ./srcs/secrets/db_root_password
  db_name:
    file: ./srcs/secrets/db_name
  db_user:
    file: ./srcs/secrets/db_user
  db_password:
    file: ./srcs/secrets/db_password